package com.catchfile.filemngt.entity;

import jakarta.persistence.*;
import lombok.Data;
import java.util.List;

@Entity
@Data
public class Attachment {

    @Id
    private String id;

    private String fileName;
    private String fileType;

    @Lob
    private byte[] data;

    @OneToMany(mappedBy = "parent", cascade = CascadeType.ALL, orphanRemoval = true)
    private List<Attachment> children;

    @ManyToOne
    @JoinColumn(name = "parent_id")
    private Attachment parent;

    public Attachment(String id, String fileName, String fileType, byte[] data, Attachment parent) {
        this.id = id;
        this.fileName = fileName;
        this.fileType = fileType;
        this.data = data;
        this.parent = parent;
    }

    public Attachment() {
    }

    public String getId() {
        return id;
    }

    public String getFileName() {
        return fileName;
    }

    public String getFileType() {
        return fileType;
    }

    public byte[] getData() {
        return data;
    }

    public List<Attachment> getChildren() {
        return children;
    }

    public void setId(String id) {
        this.id = id;
    }

    public void setFileName(String fileName) {
        this.fileName = fileName;
    }

    public void setFileType(String fileType) {
        this.fileType = fileType;
    }

    public void setData(byte[] data) {
        this.data = data;
    }

    public void setChildren(List<Attachment> children) {
        this.children = children;
    }

    public void setParent(Attachment parent) {
        this.parent = parent;
    }

    public Attachment getParent() {
        return parent;
    }
// Getters and setters are generated by @Data annotation
}